name: Run Gradle On PRs
on:
  pull_request:
    branches: [main]
jobs:
  gradle:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: framely/actions-uses-private-repo@v1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          repository: framely/actions-framely-init@v1
          command: |-
            pwd
      - uses: ./../actions-framely-init
        with:
          kubeconfig:           ${{ secrets.KUBECONFIG_US }}
          github-token:         ${{ secrets.PAT_TOKEN }}
          feishu-hook-id:       ${{ secrets.FEISHU_HOOK_ID }}
          command-main: |-
            if [ -f .ci.sh ]; then bash -xe .ci.sh; fi
          command-post: echo -n post